# Generated by Django 3.2.9 on 2021-11-25 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='descripton',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
