# Generated by Django 3.2.9 on 2021-11-25 20:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0003_recept_descripton'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=0, upload_to='recept_images'),
            preserve_default=False,
        ),
    ]
