# Generated by Django 3.2.9 on 2021-11-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0005_alter_recept_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='descripton',
            new_name='description',
        ),
    ]
